### ISSUE TITLE
Unscope 1-1 associations

### ISSUE THREAD

**Issue by barthez** [simi/mongoid_paranoia#31]
Hi,

I have struggle problem similar to #24, and overcame gem limitations by overwriting associations getter. All stuff is done in simple module:

``` ruby
module ParanoidAssociations
  extend ActiveSupport::Concern

  module ClassMethods
    def paranoid_association(*assoc)
      assoc.each do |name|
        unscope_single_association(name)
      end
    end

    private

    def unscope_single_association(name)
      klass = reflect_on_association(name).klass

      unscoped = Module.new do
        define_method(name) do |reload = false|
          klass.unscoped { super(reload) }
        end
      end

      prepend unscoped
    end
  end
end
```

Only thing you have to do is to call `paranoid_association :model` right after `belongs_to :model`. Are you interested in introducing such functionality into your gem @simi? If you are, I could prepare PR with all stuff included.

I notice that you support `jruby` so module have to be rewritten to use `alias_method_chain` instead of `prepend`.

**Comment by aCandidMind** [comment]
@barthez do you think that it is still needed to switch from `prepend` to `alias_method_chain`? I'm asking because this [issue](https://github.com/jruby/jruby/issues/2864) seemingly got fixed. But I have no idea of JRuby.

**Comment by barthez** [comment]
This gem supports jruby 1.7.19 which reflects ruby 1.9.3 (no `prepend` method). It will work with jruby9000. If you are using MRI you can use prepend without any problem.

**Comment by johnnyshields** [comment]
I believe we should drop support for JRuby 1.7.x and only support 9000.

Most legacy JRuby users would be using Rails 3 / Mongoid 3 anyway which doesn't require this gem. I imagine the number of users on legacy JRuby but newer Rails (4.x+) is very small.
