### ISSUE TITLE
including Mongoid::Paranoia changes the update method from public to private

### ISSUE THREAD

**Issue by maxjacobson** [simi/mongoid_paranoia#39]
```ruby
class Human
  include Mongoid::Document
end
human = Human.create #=> #<Human _id: 5605a9a71942d01471000002, >
human.update #=> true
Mongoid::Compatibility::Version.mongoid5? #=> true
class Robot
  include Mongoid::Document
  include Mongoid::Paranoia
end
robot = Robot.create #=> #<Robot _id: 5605a9d11942d01471000003, deleted_at(deleted_at): nil>
robot.update
# NoMethodError: private method `update' called for #<Robot:0x00000103c2ecd8>
```

The update method: https://github.com/mongodb/mongoid/blob/ffad088b8c75390d01424494f17eb25ac285db90/lib/mongoid/persistable/updatable.rb#L40-L54

**Comment by simi** [comment]
@dblock this is related to https://github.com/simi/mongoid_paranoia/blob/b7631cee2a1c120ba277174500753e8b8ff586c2/lib/mongoid/paranoia.rb#L196-L207. Should we use better name for that method like `_paranoia_update` or similar

**Comment by dblock** [comment]
@simi Sounds like it!
