### ISSUE TITLE
Rails 5 incompatibility

### ISSUE THREAD

**Issue by b-lambert** [simi/mongoid_paranoia#42]
I'm trying to upgrade a Rails application to the Rails 5 beta, which requires `activesupport = 5.0.0.beta2`. The application uses `mongoid-paranoia` `1.3.0`, which relies on `activesupport ~> 4.0`. This makes the Rails 5 beta incompatible with mongoid-paranoia.

**Comment by simi** [comment]
Any mongoid released version is not compatible with Rails 5, but there's [PR opened](https://github.com/mongodb/mongoid/pull/4234) for that. You can try this for now:

```ruby
# Gemfile
source "https://rubygems.org"

gem 'rails', '5.0.0.beta2'
gem 'mongoid_paranoia'
gem 'mongoid', git: 'https://github.com/estolfo/mongoid.git', branch: 'MONGOID-4218-rails-5'
```
