### ISSUE TITLE
Rails5: NoMethodError: private method `update' called for 

### ISSUE THREAD

**Issue by gkunwar** [simi/mongoid_paranoia#47]
I found following error when I tried to use mongoid_paranoia with rails5. I am using latest version of mongoid_paranoia (i.e. 0.2.1).

```
NoMethodError: private method `update' called for #<Mongo::Collection::View:0x007fdc7e323b08>
Did you mean?  update_one
from /Users/MAC/.rvm/gems/ruby-2.3.1@effect/gems/mongoid_paranoia-0.2.1/lib/mongoid/paranoia.rb:204:in `_paranoia_update'
```

**Comment by simi** [comment]
@gkunwar hello, can you try latest master in Gemfile?

```ruby
gem 'mongoid_paranoia', github: 'simi/mongoid_paranoia'
```

**Comment by gkunwar** [comment]
@simi Thank you for your suggestion. I'll try.

**Comment by gkunwar** [comment]
@simi Its works. Thanks.

**Comment by simi** [comment]
@gkunwar release is around the corner. I'm waiting for Mongoid 6 to be released.

**Comment by gkunwar** [comment]
@simi Thanks for update.
