### ISSUE TITLE
Transfer mongoid_paranoia to github/mongoid?

### ISSUE THREAD

**Issue by dblock** [simi/mongoid_paranoia#49]
I had https://github.com/mongoid kindly donated to the community by the nice folks at MongoDB. The three people who have org level admin access are currently @durran, @estolfo and myself. 

I want to invite this project to be moved to the org. I think it makes good sense to group mongoid projects together and have continuous support from MongoDB, the company, over the long term. All admins of this project will continue having admin access of course, but this would reduce the bus factor since currently only @simi can add maintainers here. 

If you think it's a good idea, please transfer this project to me and I'll move it into the org and please add `dblock@dblock.org`, `emily@mongodb.com` and `durran@gmail.com` to rubygems.

**Comment by johnnyshields** [comment]
:+1: I support this. Mongoid Paranoia has lots of overlap with various other Mongoid-related gems and centralizing the ownership is good idea.

**Comment by simi** [comment]
Hi! Not bad idea at all.

*Is there any chance to rename  https://github.com/mongoid to  https://github.com/mongoid-{extras,addons} or something similar and more descriptive?*

**Comment by dblock** [comment]
@simi I would rather keep github.com/mongoid as is, because I suspect one day MongoDB will want to move mongoid itself back into that org ;)

**Comment by simi** [comment]
Word!

I'll ping here once it will be done (I'm Indonesia right now not on good connection and having some troubles). Please wait few days.

**Comment by Fudoshiki** [comment]
@dblock  Hello, what do you thing about mongoid_includes and mongoid-observers gems?

**Comment by dblock** [comment]
Thanks @Fudoshiki, happy to!

**Comment by dblock** [comment]
@simi lets do it? If you transfer this repo to me I can move it to the mongoid org.

@Fudoshiki same for other gems.

**Comment by Fudoshiki** [comment]
@simi ping

**Comment by Fudoshiki** [comment]
@simi ping

**Comment by Fudoshiki** [comment]
@simi  how are u)

**Comment by Fudoshiki** [comment]
@simi ping

**Comment by Fudoshiki** [comment]
Hello @simi , what do you think?

**Comment by simi** [comment]
Hello, I'm sorry, but I see no reason to move this repo anywhere. I'm active maintainer and I'm not the only one. If you would like to contribute, feel free to here. Once I'll change my opinion, I'll reopen this issue and ping you.

Thanks for offer anyway.

**Comment by Fudoshiki** [comment]
Sure, thank you)

**Comment by dblock** [comment]
Thanks Simi. If something happens to you though there's no way to recover admin rights to the repo. Let us know if you reconsider.
