### ISSUE TITLE
Test failures in Ruby 2.4

### ISSUE THREAD

**Issue by skalee** [simi/mongoid_paranoia#53]
When I've tried to run the test suite in Ruby 2.4, I've observed two quirks:

1) A lot of weird stdout output in specs for `Mongoid::Attributes::Nested`:
```
/Users/skale/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/locale/en.yml
yml
/Users/skale/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/locale/en.yml
/Users/skale/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/locale/en.yml
/Users/skale/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.0.2/lib/active_model/locale/en.yml
yml
/Users/skale/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.0.2/lib/active_model/locale/en.yml
/Users/skale/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.0.2/lib/active_model/locale/en.yml
/Users/skale/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/mongoid-6.1.0/lib/config/locales/en.yml
yml
/Users/skale/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/mongoid-6.1.0/lib/config/locales/en.yml
/Users/skale/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/mongoid-6.1.0/lib/config/locales/en.yml
```

2) Weird spec failures, e.g.
```
  1) Mongoid::Paranoia#restore when the document is a root marks document again as persisted
     Failure/Error: paranoid_collection.find(atomic_selector).update_one(value)

     TypeError:
       wrong argument type Integer (expected Proc)
     # ./lib/mongoid/paranoia.rb:200:in `_paranoia_update'
     # ./lib/mongoid/paranoia.rb:102:in `remove'
     # ./spec/mongoid/paranoia_spec.rb:674:in `block (4 levels) in <top (required)>'
```

The interesting thing about the problem no. 2 is that that the first of the problematic examples always passes. For example, running any of failing tests alone results with passing test. There must be some interference between examples.

Neither of above happens in Ruby 2.3.

**Comment by skalee** [comment]
Actually, looks like exceptions are pretty random, the number of failures ranges from 6 to 8.

**Comment by simi** [comment]
Hello. Thanks for report. I just started CI build for 2.4 (https://travis-ci.org/simi/mongoid_paranoia/jobs/218280243) and I'll try to fix this.

**Comment by skalee** [comment]
Yes, I saw your build. However I run my tests in Ruby 2.4.0, not 2.4.1, perhaps this is the reason? I'll install the newest Ruby and see what happens.

**Comment by skalee** [comment]
The build has been fixed on my computer after upgrading Ruby from 2.4.0 to 2.4.1. Thanks!

Also, I see another weird failures for jruby, perhaps it's worth to change "jruby-9.1.2.0" in Travis to just "jruby"? Could be it.

**Comment by simi** [comment]
I see some errors on 2.4.0 on CI now (https://travis-ci.org/simi/mongoid_paranoia/jobs/218281669). Yup, I see JRuby fails also. I'll try to handle JRuby errors soon. Thanks for report. Feel free to close this if you're ok with Ruby 2.4.1 update.

**Comment by skalee** [comment]
Thank you too. Yes, I'm happy with resolution.
