### ISSUE TITLE
undefined method `alias_method_chain' for Mongoid::Paranoia:Module

### ISSUE THREAD

**Issue by HudsonAfonso** [simi/mongoid_paranoia#56]
`rescue in block (2 levels) in require': There was an error while trying to load the gem 'mongoid_paranoia'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `alias_method_chain' for Mongoid::Paranoia:Module

**Comment by simi** [comment]
Hello! Can you post more details? At least `mongoid_paranoia` version? Also can you try latest release?

**Comment by johnnyshields** [comment]
Repo no longer uses alias_method_chain, so this should not be an issue.
