### ISSUE TITLE
Doesn't work with Mongoid 7

### ISSUE THREAD

**Issue by stanley90** [simi/mongoid_paranoia#58]
Mongoid 7 is in beta, but should have next release rather soon.

```
Bundler::GemRequireError:
  There was an error while trying to load the gem 'mongoid_paranoia'.
  Gem Load Error is: Cannot define multiple 'included' blocks for a Concern
  Backtrace for gem load error is:
  /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/activesupport-5.1.4/lib/active_support/concern.rb:126:in `included'
  /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid_paranoia-0.3.0/lib/mongoid/paranoia/monkey_patches.rb:7:in `<module:Document>'
  /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid_paranoia-0.3.0/lib/mongoid/paranoia/monkey_patches.rb:4:in `<module:Paranoia>'
  /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid_paranoia-0.3.0/lib/mongoid/paranoia/monkey_patches.rb:3:in `<module:Mongoid>'
  /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid_paranoia-0.3.0/lib/mongoid/paranoia/monkey_patches.rb:2:in `<top (required)>'
  /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid_paranoia-0.3.0/lib/mongoid/paranoia.rb:2:in `require'
  /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid_paranoia-0.3.0/lib/mongoid/paranoia.rb:2:in `<top (required)>'
  /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid_paranoia-0.3.0/lib/mongoid_paranoia.rb:1:in `require'
  /Users/stanley/.rvm/gems/ruby-2.5.0@redclover/gems/mongoid_paranoia-0.3.0/lib/mongoid_paranoia.rb:1:in `<top (required)>'
```

**Comment by Fudoshiki** [comment]
@stanley90 if you need working paranoid documents with mongoid 7.0 now https://github.com/Fudoshiki/mongoid-paranoid

Usage example, callbacks and methods same as in **mongoid-paranoia**
```ruby

#   class User
#     include Mongoid::Document
#     include Paranoid.new default_scope: false, field: :d_at
#   end
```
[mongoid-slug](https://github.com/Fudoshiki/mongoid-paranoid) version for [mongoid-paranoid](https://github.com/Fudoshiki/mongoid-paranoid), will open PR soon in [original repo](https://github.com/mongoid/mongoid-slug ) for adding compatibility with **mongoid-paranoia** and **mongoid-paranoid** together and add the tests and documentation in **mongoid-paranoid**

**Comment by theomarkkuspaul** [comment]
Mongoid 7 has had an official release and we are keen to have use this gem with the latest version. Does anyone know what the situation is with this issue?

**Comment by simi** [comment]
@tagliala this gem is maintained, but it is hard for me to find time to prepare new release these days and both PRs you have mentioned are breaking CI and thus it is not easy for me to merge them without any additional work.

If you want to help, you can try to provide needed change with green build or help in those PRs make build green. That will make process of releasing new version much faster.

**Comment by tagliala** [comment]
@simi I'm glad to help

Please take a look at #61

**Comment by tagliala** [comment]
@simi is there anything else I can do?
