### ISSUE TITLE
Not working with Mongoid 7.1 changes to `or` behavior

### ISSUE THREAD

**Issue by ababich** [simi/mongoid_paranoia#65]
Please, see https://docs.mongodb.com/mongoid/7.1/tutorials/mongoid-upgrade/#upgrading-to-mongoid-7-1

❗ Maybe not limited to `or`

Examples:
`pre 7.1`
```
> ParanoiaModel.or(A).or(B).selector

{"deleted_at"=>nil, "$or"=>[A, B]}
```

`7.1+`:
```
> ParanoiaModel.or(A).or(B).selector

{"$or"=>[{"deleted_at"=>nil}, A, B]}
```

**Comment by johnnyshields** [comment]
Can you test this on 7.2 and re-open if needed? We use a `default_scope` for the `deleted_at: nil` part, so this is really a bug in Mongoid itself; default_scopes should always be AND'ed, not OR'ed.
